applications:
  - key: bookverse-web
    seeds:
      application: 2.4.16
      build: 3.7.25
    packages:
      - type: docker
        name: web
        seed: 1.6.14
      - type: generic
        name: web-assets.tar.gz
        seed: 3.31.39
