applications:
  - key: bookverse-web
    seeds:
      application: 1.7.2
      build: 2.18.9
    packages:
      - type: docker
        name: web
        seed: 1.8.15
      - type: generic
        name: web-assets
        seed: 1.8.15
